[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "advent_of_code_2022"
path = "src/lib.rs"

[dependencies]
binary-heap-plus = "0.5.0"
num = "0.4.3"
