[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dict = "0.1.5"
itertools = "0.12.0"
memoize = "0.4.1"
num = "0.4.1"
num-traits = "0.2.17"
regex = "1.10.2"
serde = {version="1.0.193", features=["derive"]}
serde_json = "1.0.108"
