name: Run formatter

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Run linter 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cd rust-projects && 
          cargo fmt -- --check
